version: '3'

services:
  
  jenkins:
    build: jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    depends_on:
      - wingman

  wingman:
    build: 
      context: orchestrator
      args:
        - GIT_USER_NAME=${GIT_USER_NAME:-Tiago Santos}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL:-tsantos@pentaho.com}
        - uid=${USERID:-1000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - git-sources:/home/buildguy/wingman/source
      - maven-cache:/home/buildguy/.m2/repository
    # ports:
    #  - "8181:8181"
    healthcheck:
      test: ["CMD", "/home/buildguy/wingman/bin/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  git-sources:
  maven-cache:
    driver_opts:
      type: none
      device: ${HOME}/.m2/repository
      o: bind